add salaries
coopTilleuls/.github pull request #54
Opened 2022-11-29 10:50 UTC by dunglas

To transform an XLS in a Markdown table: https://tableconvert.com/

2022-11-29 10:58 UTC, Deuchnord requested changes

2022-11-29 10:58 UTC, Deuchnord commented on profile/salaries/README.md
> +Chez Les-Tilleuls.coop, tous les salarié•es sont placé sur une grille disposant de 6 niveaux, qui dépendent des compétences et de l'expérience.
```suggestion
Chez Les-Tilleuls.coop, tous les salarié•es sont placé•es sur une grille disposant de 6 niveaux, qui dépendent des compétences et de l'expérience.
```

2022-11-29 10:58 UTC, Deuchnord commented on profile/salaries/README.md
> +1. un salaire fixe déterminé par la place dans les grilles (toutes les personne au même niveau ont le même salaire fixe)
```suggestion
1. un salaire fixe déterminé par la place dans les grilles (toutes les personnes au même niveau ont le même salaire fixe)
```

2022-11-29 10:58 UTC, Deuchnord commented on profile/salaries/README.md
> +2. la participation aux bénéfices : 80 % des bénéfices réalisés par la coopératives sont répartis égalitairement entre toutes et tous les salarié•es, au prorata du temps de travail annuel effectif (l
```suggestion
2. la participation aux bénéfices : 80 % des bénéfices réalisés par la coopérative sont répartis égalitairement entre toutes et tous les salarié•es, au prorata du temps de travail annuel effectif (les 20 % restants sont mis en réserve pour investir et faire face à d’éventuels coups durs). Cette prime peut être prise immédiatement ou au bout de 5 ans, auquel cas elle n'est pas imposable. Elle peut également être débloquée exceptionnellement [dans certains cas de figure prévus par la loi](https://www.service-public.fr/particuliers/vosdroits/F31622).
```

2022-11-29 10:58 UTC, Deuchnord commented on profile/salaries/README.md
> +* Chèques lire
C'est pas la même chose que les chèques culture ?

2022-11-29 11:00 UTC, dunglas commented on profile/salaries/README.md
> +* Chèques lire
Non !

2022-11-29 11:05 UTC, Gregcop1 commented on profile/salaries/README.md
> +* [Lire sur le blog le processur d'élaboration de cette grille](https://les-tilleuls.coop/blog/grille-salariale-a-vote)
```suggestion
* [Lire sur le blog le processus d'élaboration de cette grille](https://les-tilleuls.coop/blog/grille-salariale-a-vote)
```

2022-11-29 11:58 UTC, chalasr commented on profile/salaries/README.md
> +| **2020**           | 5754    |
On a une explication pour la baisse par rapport à 2019 ? Augmentation de la masse salariale suite à réévalutation post définition de la grille ? Ce serait bien de le préciser aussi j'pense.

2022-11-29 12:36 UTC, ArnoudThibaut commented on profile/salaries/README.md
> +| **2020**           | 5754    |
C'est l'année des confinements, du chomage partiel etc donc je pense que ça vient de là cette baisse sur 2020

2022-11-29 13:28 UTC, dunglas commented on profile/salaries/README.md
> +| **2020**           | 5754    |
Et surtout il n'y a pas la prime macron, qui n'apparaît ni ici, ni dans partie salaire...

2022-11-30 08:06 UTC, ArnoudThibaut commented on profile/salaries/README.md
> +| **2020**           | 5754    |
Ouais c'est surement aussi ça. En vérifiant la date de création de la prime j'ai vu qu'elle date de 2019 donc je pensais qu'on se l'était versée aussi en 2019 mais faut croire que non, j'ai pas vu de trace en re-vérifiant

2022-11-30 14:09 UTC, eliseduverdier commented on profile/titles/README.md
> +
On peut supprimer le tableau commenté en bas de ce fichier du coup :)

2022-11-30 14:09 UTC, eliseduverdier commented on profile/salaries/README.md
> +| **2 ans**                |                        |                      |                     | **5 ans**                  |                                        |
Attention il y un décalage, le tableau commence à 2 ans :
![Screenshot from 2022-11-30 15-06-52](https://user-images.githubusercontent.com/4543769/204817037-81f2c6be-a63f-4d13-9bec-33068ad6a28e.png)

D'ailleurs je serais d'avis de mettre uniquement les salaires de départ, pour rendre la grille plus lisible aux candidats, qui seront concernés uniquement par celle-ci,

Quitte à garder une version en interne ailleurs pour nous :)

2022-11-30 16:01 UTC, assimakis requested changes

2022-11-30 16:01 UTC, assimakis commented on profile/salaries/README.md
> +* [Chèques Culture](https://up.coop/cheque-culture/utiliser-cheque-culture/)
```suggestion
* [Chèques Culture](https://up.coop/cheque-culture/utiliser-cheque-culture/) (100€/an)
```

2022-11-30 16:47 UTC, pborreli commented on profile/salaries/README.md
> +* [Chèques Déjeuner](https://up.coop/updejeuner/employeurs)
je mettrais le lien https://up.coop/updejeuner/utilisateurs/ plutôt

2022-11-30 19:26 UTC, assimakis requested changes

2022-11-30 19:26 UTC, assimakis commented on profile/salaries/README.md
> +| Chèques Lire           | 100€               | 0€                 |
```suggestion
| Chèques culture        | 100€               | 0€                 |
| Prime télétravail      | 20€                | 0€                 |

2022-11-30 19:26 UTC, assimakis commented on profile/salaries/README.md
> +* Congé sans solde illimité
```suggestion
* Congé sans solde illimité
* Liberté dans la pose des congés 
* Possibilité de poser des congés par anticipation (congés acquis) 
```

2022-11-30 19:26 UTC, assimakis commented on profile/salaries/README.md
> +* Carte Liberté pour les coopérateurs des agences et ceux qui voyagent régulièrement (379€)
```suggestion
* Carte Liberté pour les coopérateurs des agences et ceux qui voyagent régulièrement (379€)
* Nombreuses formations interne ( pôle formation ) 
* Participation à des conférences (budget de 1000€/an)

```

2022-11-30 19:55 UTC, pborreli commented on profile/salaries/README.md
> +* [Chèques Déjeuner](https://up.coop/updejeuner/employeurs). Possibilité de choisir entre la carte ou les chèques papier. Valeur unitaire de 10€ avec prise en charge par la SCOP à hauteur de 6€ et 4€
```suggestion
* [Chèques Déjeuner](https://up.coop/updejeuner/utilisateurs). Possibilité de choisir entre la carte ou les chèques papier. Valeur unitaire de 10€ avec prise en charge par la SCOP à hauteur de 6€ et 4€ par le coopérateur.
```

2022-11-30 19:57 UTC, pborreli commented on profile/salaries/README.md
> +* Carte Liberté pour les coopérateurs des agences et ceux qui voyagent régulièrement (379€)
```suggestion
* Carte SNCF Liberté pour les coopérateurs en ayant besoin (379€)
```

2022-11-30 20:19 UTC, assimakis approved these changes

2022-11-30 20:19 UTC, assimakis commented on profile/salaries/README.md
> +* [Chèques Déjeuner](https://up.coop/updejeuner/employeurs). Possibilité de choisir entre la carte ou les chèques papier. Valeur unitaire de 10€ avec prise en charge par la SCOP à hauteur de 6€ et 4€
```suggestion
* [Chèques Déjeuner](https://up.coop/updejeuner/employeurs). Possibilité de choisir entre la carte ou les chèques papier. Valeur unitaire de 10€ avec prise en charge par la SCOP à hauteur de 5,20€ et 4,80€ par le coopérateur.
```

2022-12-01 07:18 UTC, norival commented on profile/salaries/README.md
> +* [Voir les compétences associés aux titres](../titles/README.md)
```suggestion
* [Voir les compétences associées aux titres](../titles/README.md)
```

2022-12-01 08:08 UTC, assimakis approved these changes

2022-12-01 08:08 UTC, assimakis commented on profile/salaries/README.md
> +* [Congé menstruel](https://les-tilleuls.coop/blog/conge-menstruel)
```suggestion
* [Congé menstruel](https://les-tilleuls.coop/blog/conge-menstruel)
* 3 jours de congés payés enfants malades 
* 3 jours de congés "aléas de la vie" pour les postes de Junior programmer et Programmer
* Congés d'ancienneté: 1 jour après 5 ans/ 2 jours après 10 ans / 3 jours après 15 ans / 4 jours après 20 ans
```

2022-12-05 14:54 UTC, merged