Fix inclusive words
coopTilleuls/.github pull request #57
Opened 2022-12-01 08:36 UTC by vincentchalamon

2022-12-01 14:48 UTC, eliseduverdier commented
Sans vouloir être relou, il me semble qu'il faut utiliser le point median « · » et pas le bullet « • » :slightly_smiling_face:

2022-12-02 11:04 UTC, alanpoulain approved these changes

2022-12-08 10:57 UTC, dunglas requested changes

2022-12-08 10:57 UTC, dunglas commented on profile/revenues/README.md
> -| **Junior Programmer**    | 24 504,00 €                |
On peut laisser le titres en anglais stp ? C'est neutre de base comme ça en plus.

2022-12-08 10:57 UTC, dunglas commented on profile/revenues/README.md
> +Note : la baisse post-2018 s'explique par l'expiration du statut [Jeune Entreprise Innovante](https://entreprendre.service-public.fr/vosdroits/F31188) de la coopérative, et par la mise en place de la
Ils l'écrivent sans majuscules sur le site du gouvernement en lien.

2022-12-08 10:57 UTC, dunglas commented on profile/revenues/README.md
> +* [Chèques Déjeuner](https://up.coop/updejeuner/utilisateurs) ; possibilité de choisir entre la carte ou les chèques papiers ; valeur unitaire de 10 € avec prise en charge à hauteur de 5,20 € par la
```suggestion
* [Chèques Déjeuner](https://up.coop/updejeuner/utilisateurs) ; possibilité de choisir entre la carte ou les chèques papiers ; valeur unitaire de 10 € avec prise en charge à hauteur de 5,20 € par la coopérative et 4,80 € par la ou le coopérateur·rice
```

(mais ça fait lourd)

2022-12-08 10:57 UTC, dunglas commented on profile/revenues/README.md
> +| **Développeur.euse junior**      | 24 504,00 €                |
En plus c'est pas les bons points médians :D

2022-12-08 10:57 UTC, dunglas commented
Sinon pour pinailler, pour l'accessibilité aux personnes handicapées il vaudrait mieux utiliser la forme étendue :  https://access42.net/langage-non-genre-accessibilite

2022-12-08 11:00 UTC, dunglas commented on profile/revenues/README.md
> +* [Chèques Déjeuner](https://up.coop/updejeuner/utilisateurs) ; possibilité de choisir entre la carte ou les chèques papiers ; valeur unitaire de 10 € avec prise en charge à hauteur de 5,20 € par la
```suggestion
* [Chèques Déjeuner](https://up.coop/updejeuner/utilisateurs) ; possibilité de choisir entre la carte ou les chèques papier ; valeur unitaire de 10 € avec prise en charge à hauteur de 5,20 € par la coopérative et 4,80 € par le/la coopérateur·rice
```

Pas de s à "papier" dans ce cas il me semble

2022-12-08 11:00 UTC, dunglas commented on profile/revenues/README.md
> +* [Chèques Déjeuner](https://up.coop/updejeuner/utilisateurs) ; possibilité de choisir entre la carte ou les chèques papiers ; valeur unitaire de 10 € avec prise en charge à hauteur de 5,20 € par la
Je confirme : https://www.question-orthographe.fr/question/documents-papiers/

2022-12-08 11:02 UTC, vincentchalamon commented on profile/revenues/README.md
> -| **Junior Programmer**    | 24 504,00 €                |
J'ai repris les intitulés décrits sur la page [Titres de développeurs](https://github.com/coopTilleuls/.github/blob/main/profile/titles/README.md), et les ai décliné en écriture inclusive.

IMHO, on devrait les mettre en anglais partout alors.

2022-12-09 12:21 UTC, eliseduverdier commented on profile/README.fr.md
> +* [📚 PHP Standard Library](https://github.com/azjezz/psl) : un ensemble d'APIs pour les devs PHP
Normalement les apostrophes typographiques correctes sont bien les `’`, le changement a été fait exprès ou automatiquement ?

Cf [doc wiktionary](https://fr.wiktionary.org/wiki/%27)

2022-12-09 13:21 UTC, vincentchalamon commented on profile/README.fr.md
> +* [📚 PHP Standard Library](https://github.com/azjezz/psl) : un ensemble d'APIs pour les devs PHP
C'est un changement fait exprès car mon clavier (comme plein d'autres claviers) ne propose pas cette apostrophe.
Faut-il remplacer toute occurence de cette nouvelle apostrophe par l'apostrophe typographique, dans tout le projet ?

2022-12-09 16:47 UTC, eliseduverdier commented on profile/README.fr.md
> +* [📚 PHP Standard Library](https://github.com/azjezz/psl) : un ensemble d'APIs pour les devs PHP
Les nazis de la typographie diraient que oui, il faut utiliser les vraies apostrophes :grin: 
Après sans se prendre la tête, il me semblait les avoir ajouté au début, mais ce n'est pas grave s'il en reste :)

Pour info, il est accessible sur les claviers linux (en _French (alt.)_) avec `alt gr+G`,

Et bon à savoir, voilà comment faire les vrais apostrophes sur linux :
![Screenshot from 2022-12-09 17-40-25](https://user-images.githubusercontent.com/4543769/206750521-62fc4ae8-e92d-43b4-800f-b83edbfc3991.png)

Sur Mac c'est possible facilement aussi (raccourcis visibles avec le visualisateur de clavier)

2022-12-09 21:35 UTC, vincentchalamon commented on profile/README.fr.md
> +* [📚 PHP Standard Library](https://github.com/azjezz/psl) : un ensemble d'APIs pour les devs PHP
Fixed.

2022-12-12 11:40 UTC, eliseduverdier approved these changes

2022-12-12 17:26 UTC, dunglas requested changes

2022-12-12 17:26 UTC, dunglas commented on profile/README.md
> -# 👋️ Welcome on Les-Tilleuls.coop's GitHub page!
Il faut laisser les apostrophes d'origine pour les contenus en anglais.

2022-12-12 17:28 UTC, vincentchalamon commented on profile/README.md
> -# 👋️ Welcome on Les-Tilleuls.coop's GitHub page!
Fixed

2022-12-12 21:35 UTC, merged

2022-12-12 21:35 UTC, dunglas commented
Merci @vincentchalamon !